### ISSUE TITLE
Fix issues causing the pipeline to fail

### ISSUE THREAD

**Issue by fuddin95** [sachai-kya-hai/sachai_ui#16]
We have build pipelines now, 
it checks for some code queality that deployment servers will also check, therefore if we can keep the code clean it will be easy to deploy 
https://github.com/sachai-kya-hai/sachai_ui/actions/runs/5703665102/job/15456531984?pr=14
<img width="898" alt="Screenshot 2023-07-30 at 6 57 24 AM" src="https://github.com/sachai-kya-hai/sachai_ui/assets/61559675/777d3911-be33-45ed-bfa9-c40f567f1dc6">

**Comment by hassanzareef** [comment]
Redux Links I was using for ThunkAPI:

https://redux-toolkit.js.org/api/createAsyncThunk

https://www.youtube.com/watch?v=93CR_yURoII

**Comment by fuddin95** [comment]
#18
